version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  # image: activenode/listmonk-arm64:latest
  image: activenode/listmonk:latest
  ports:
    - "9087:9000"
  networks:
    - listmonk
    - web
  environment:
    - TZ=Europe/Berlin

x-db-defaults: &db-defaults
  image: postgres:15
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=listmonkdb
    - POSTGRES_USER=listmonkdb
    - POSTGRES_DB=listmonkdb
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    hostname: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    depends_on:
      - db
    command:
      [
        # also add copying a secret from /run/secrets/config.toml to /listmonk/config.toml if exists
        "./listmonk",
        "--install",
        "--idempotent",
        "--yes",
        "--continue-after-install",
        "--config=/run/secrets/listmonk_config_toml",
      ]
      # alternative:
      # using idempotent with &&
      # command: [sh, -c, "yes | ./listmonk --install --idempotent --config ... && ./listmonk --config config-demo.toml"]
    secrets:
      - listmonk_config_toml

networks:
  listmonk:
  web:
    # external: true

secrets:
  listmonk_config_toml:
    external: true

volumes:
  listmonk-data:
