version: "3.7"

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: activenode/listmonk:latest
  ports:
    - "9087:9000"
  networks:
    - listmonk
    - web
  environment:
    - TZ=Europe/Berlin

x-db-defaults: &db-defaults
  image: postgres:15
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=listmonk_pass
    - POSTGRES_USER=listmonk_user
    - POSTGRES_DB=listmonkdb
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    hostname: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    volumes:
      - type: volume
        source: listmonk-uploads
        target: /listmonk/uploads
    depends_on:
      - db
    command:
      [
        "./listmonk",
        "--install",
        "--idempotent",
        "--yes",
        "--continue-after-install",
        "--config=/run/secrets/listmonk_config_toml",
      ]
      # alternative:
      # using idempotent with &&
      # but that would need sh -c and isn't just one process...
      # command: [sh, -c, "yes | ./listmonk --install --idempotent --config ... && ./listmonk --config config-demo.toml"]
    secrets:  # < remove me if you wanna use the config-demo.toml with volumes instead
      - listmonk_config_toml

networks:
  listmonk:
  web: # for reverse proxy for example. if you dont have / use one, just remove this
    external: true

secrets: # remove me if you wanna use the config-demo.toml with volumes instead
  listmonk_config_toml:
    external: true

volumes:
  listmonk-data:
  listmonk-uploads:
